version: '3'
services:
  nats:
    image: nats
    command: '--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222'
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
  nats-1:
    image: nats
    command: '--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222'
  nats-2:
    image: nats
    command: '--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222'
networks:
  default:
    name: nats
